### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by mattheyan** [davotronic5000/PowerShell_Credential_Manager#10]
Hi Dave,

First of all, this module looks pretty sweet! I tried it out and it worked like a charm.

In terms of licensing, I wonder why you chose to go with GPL? This has come up as an issue at work in the past. The fear and uncertainty of GPL licensed code is enough to make me think twice about using it at my day job.  If nothing else, I'm never going to be knowledgeable enough of the legal implications to feel confident that its worth the risk. Its obviously perfectly fine to install the module on a machine and use it, but what about tools that might take it as a dependency, or bundle it or repackage it in some way?

Anyway, I'm sure I'm not the only person who will ever encounter this question, so I just wanted to make sure you had considered this when choosing the license. Feel free to ignore this or close it as you see fit...

-Bryan

**Comment by davotronic5000** [comment]
Hi Bryan

To be honest, I don't think I ever made the choice of GPL, it was just the one I happened to pick when setting up the repo in GitHub.  I am currently doing a bit of reading on the different licences, to find the best fit for what I want, with an aim to change the licence in line with the next release of the module.

I am thinking the most likely license will be the MIT license, as long as the attribution is there, I don't really care what people do with the code.

Thanks
Dave

**Comment by mattheyan** [comment]
Awesome! I think most people would be comfortable with MIT. And I get why you'd want attribution. I would definitely make sure to do that if I ever used this in a derived work.

Just out of curiosity, when do you think v2 will be released?

Thanks

**Comment by davotronic5000** [comment]
I am hoping to have something out this weekend, just need some testing and finish off updating the help files.

**Comment by davotronic5000** [comment]
MIT license has been implemented as of the 2.0 release of the module
