### ISSUE TITLE
PowerShell gallery appears outdated

### ISSUE THREAD

**Issue by Josverl** [davotronic5000/PowerShell_Credential_Manager#11]
It appears that the last version published to the PSGallery was on 2015-09-07, and that several useful additions have been done since.

Could you push an update 2.0 to the Powershell gallery ?
Publication of the updates to the Gallery would allow me to reference and auto-download your module from scripts I publish there, rather than having to fork and include them in my own modules.

**Comment by davotronic5000** [comment]
Yes the current version on the PSGallery is 1.1, although I may not have updated the version number in the metadata.  This is the latest stable version.  I have v2 close to release, main thing remaining is getting the XML documentation working.  Once v2 goes to release I will update the PSGallery.

**Comment by davotronic5000** [comment]
The version 2 release is up on Github now, but there is an issue with my account on PowerShell Gallery.  I have contacted support and will update the files there when I can get access.

**Comment by Josverl** [comment]
Thanks :-) 
it would indeed be nice to have consistent version numbers in the gallery. For now ill take a dependency on 1.1 (1.0.0.0)
I think I have found a way to publish a script such that it automatically triggers installation of dependent modules.

**Comment by davotronic5000** [comment]
The powershell gallery is now up to date with the latest 2.0 release
