### ISSUE TITLE
Not compatible with PowerShell Core

### ISSUE THREAD

**Issue by jonathaneckman** [davotronic5000/PowerShell_Credential_Manager#23]
I get the following error with `New-StoredCredential` on PowerShell Core 7. 

```
New-StoredCredential : Argument 'New-StoredCredential' is not recognized as a cmdlet: Could not load type 'System.Web.Security.Membership' from assembly 'System
.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

The other cmdlets work in Core. All cmdlets work in PowerShell 5.

**Comment by davotronic5000** [comment]
I am not really developing at all on this project anymore, as I have little involvement with Powershell these days.  I would not expect it to work with PowerShell core as it was uses .net framework features that would not be included in core.

**Comment by grantcarthew** [comment]
Hi @davotronic5000.
I suggest you re-open this issue for visibility. I was about to raise this same problem.

**Comment by SamWalkerRxSense** [comment]
https://github.com/PowerShell/PowerShell/issues/5352
