### ISSUE TITLE
Add Command Help / Examples

### ISSUE THREAD

**Issue by MattHodge** [davotronic5000/PowerShell_Credential_Manager#7]
Hi @davotronic5000,

I like the Module and have many uses for it :)

Would be nice if you could add PowerShell help and examples to the commands.

Thanks!

**Comment by davotronic5000** [comment]
Hi Matt

There is some basic help included with the module avaialble with the Get-Help command, but I am planning to expand the help to be more complete for v3 of the module once I have complete PowerShell support working.

Thanks

**Comment by davotronic5000** [comment]
The documentaion in module has been updated and is now aut-generated at build time based on source code comments, I have also introduced online docs in the github wiki
