### ISSUE TITLE
UserName Parameter in New-StoredCredential does not store the username correctly.

### ISSUE THREAD

**Issue by MattHodge** [davotronic5000/PowerShell_Credential_Manager#8]
UserName Parameter in New-StoredCredential does not store the username correctly.

To replicate:

1. Run the following `New-StoredCredential  -Password mypassword -Persist ENTERPRISE -Target TestNewCred -Type GENERIC -UserName TestUser`
2. Run `Get-StoredCredential` and you will see a new credential was created but using the current username `($env:Username)` instead of the credential specified with the UserName param

**Comment by davotronic5000** [comment]
I have now put out release 1.1 which fixes this bug.  There was some leftover code from testing causing this.  Should be resolved now though.
